version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    platform: linux/arm64/v8
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres-data:/data/postgres
       - ./init-db:/init-db
    command: ["bash", "/init-db/init.sh"]
    ports:
      - '5432:5432'
    restart: unless-stopped
volumes:
  postgres-data:
